name: "Update Cloudflare IP Addresses"

on:
  schedule:
    - cron: '23 14 * * *' # Random time, daily
  workflow_dispatch:

jobs:
  update:
    name: "Update"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update IPs
        run: |
          curl https://www.cloudflare.com/ips-v4 -o data/v4.txt
          curl https://www.cloudflare.com/ips-v6 -o data/v6.txt

      - name: Commit & Push changes
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
